service: app

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-central-1

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}
    layers:
      - {Ref: PythonRequirementsLambdaLayer}

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: src/app.app 
  pythonRequirements:
    layer: true
