on:
  push:
    branches:
      - master
name: Deploy to Lambda
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Python environment
        uses: actions/setup-python@v1.1.1
        with:
          python-version: '3.6'

      - run: yarn install

      - run: python --version
      - run: /usr/bin/python --version
      - run: /usr/bin/python3 --version
      - run: python2 --version
      - run: python3 --version
      - run: which python

      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}